# **Part 1 — Data Loading and Initial Exploration**

1. Import the pandas library and load the dataset into a DataFrame named df.

In [62]:
import pandas as pd
df = pd.read_csv("students_performance.csv")

2. Display the first 10 rows of the dataset

In [63]:
print("First 10 rows of the dataset:")
display(df.head(10))

First 10 rows of the dataset:

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

3. Display summary information: shape of the dataset, column names, data types, missing
values, and basic statistics using .describe()

In [6]:
print("Shape of the dataset (rows, columns):")
print(df.shape)

Shape of the dataset (rows, columns):
(1000, 8)

In [9]:
print("Column names:")
print(df.columns.tolist())

Column names:
['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']

In [10]:
print("Data types:")
print(df.dtypes)

Data types:
gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [ ]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [12]:
print("Basic statistics of numerical columns:")
display(df.describe())

Basic statistics of numerical columns:

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

4. Rename columns to replace spaces with underscores for easier access (e.g.,
test_preparation_course → test_prep).

In [64]:
df.columns = df.columns.str.replace(' ', '_').str.lower()
print("Renamed columns:")
print(df.columns.tolist())

Renamed columns:
['gender', 'race/ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course', 'math_score', 'reading_score', 'writing_score']

# **Part 2 — Data Cleaning and Transformation**

5. Check for and handle missing or duplicate rows. Drop duplicates if any, and handle
missing values appropriately (justify your choice).

In [15]:
# Check for duplicates
print("Number of duplicate rows before dropping:", df.duplicated().sum())

Number of duplicate rows before dropping: 0

In [ ]:
# Drop duplicates
df = df.drop_duplicates()
print("Number of duplicate rows after dropping:", df.duplicated().sum())

Number of duplicate rows after dropping: 0

In [ ]:
# Check for missing values
print("Missing values before handling:")
print(df.isnull().sum())

Missing values before handling:
gender                         0
race/ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

In [17]:
# Handle missing values (if any)
# For this dataset, usually there are none, but if any exist:
# Then for Numeric columns: fill with mean
# For Object type or Categorical columns: fill with mode
for col in df.columns:
    if df[col].dtype != 'object':
        df[col] = df[col].fillna(df[col].mean())
    else:
        df[col] = df[col].fillna(df[col].mode()[0])

print("Missing values after handling:")
print(df.isnull().sum())

Missing values after handling:
gender                         0
race/ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

6. Create a new column average_score as the mean of (math score, reading score, writing
score).

In [18]:
df['average_score'] = df[['math_score', 'reading_score', 'writing_score']].mean(axis=1)

In [19]:
df

,gender,race/ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,average_score
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667
1,female,group C,some college,standard,completed,69,90,88,82.333333
2,female,group B,master's degree,standard,none,90,95,93,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333
4,male,group C,some college,standard,none,76,78,75,76.333333
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.000000
996,male,group C,high school,free/reduced,none,62,55,55,57.333333
997,female,group C,high school,free/reduced,completed,59,71,65,65.000000
998,female,group D,some college,standard,completed,68,78,77,74.333333
999,female,group D,some college,free/reduced,none,77,86,86,83.000000

7. Categorize students based on average_score into Fail (0–59), Pass (60–69), Merit (70–
79), and Distinction (80–100). Store this in a new column performance_category.

In [21]:
# Step 7: Categorize students based on average_score
def categorize(score):
    if score < 60:
        return 'Fail'
    elif score < 70:
        return 'Pass'
    elif score < 80:
        return 'Merit'
    else:
        return 'Distinction'

df['performance_category'] = df['average_score'].apply(categorize)
df

,gender,race/ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,average_score,performance_category
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667,Merit
1,female,group C,some college,standard,completed,69,90,88,82.333333,Distinction
2,female,group B,master's degree,standard,none,90,95,93,92.666667,Distinction
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333,Fail
4,male,group C,some college,standard,none,76,78,75,76.333333,Merit
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.000000,Distinction
996,male,group C,high school,free/reduced,none,62,55,55,57.333333,Fail
997,female,group C,high school,free/reduced,completed,59,71,65,65.000000,Pass
998,female,group D,some college,standard,completed,68,78,77,74.333333,Merit
999,female,group D,some college,free/reduced,none,77,86,86,83.000000,Distinction

8. Convert gender, parental level of education, and test_prep columns to categorical data
types using astype('category').

In [32]:
# Convert columns to categorical data type
df[['gender', 'parental_level_of_education', 'test_preparation_course']] = df[['gender', 'parental_level_of_education', 'test_preparation_course']].astype('category')

In [33]:
df.dtypes

gender                         category
race/ethnicity                   object
parental_level_of_education    category
lunch                            object
test_preparation_course        category
math_score                        int64
reading_score                     int64
writing_score                     int64
average_score                   float64
performance_category             object
dtype: object

# **Part 3 — Data Analysis and Aggregation**

9. Compute the average math, reading, and writing scores by gender.

In [35]:
# Compute the average math, reading, and writing scores by gender.
avg_scores_by_gender = df.groupby('gender', observed=True)[['math_score', 'reading_score', 'writing_score']].mean()
print("🔹 Average scores by gender:")
display(avg_scores_by_gender)

🔹 Average scores by gender:

        math_score  reading_score  writing_score
gender
female   63.633205      72.608108      72.467181
male     68.728216      65.473029      63.311203

10. Find average scores grouped by: (a) Gender and test_prep, (b) Parental level of
education.

In [38]:
# (a) Average scores grouped by gender and test preparation course
avg_by_gender_prep = df.groupby(['gender', 'test_preparation_course'], observed = True)[['math_score', 'reading_score', 'writing_score', 'average_score']].mean()
print("Average scores by Gender and Test Preparation Course:")
display(avg_by_gender_prep)

Average scores by Gender and Test Preparation Course:

                                math_score  reading_score  writing_score  \
gender test_preparation_course
female completed                 67.195652      77.375000      78.793478
       none                      61.670659      69.982036      68.982036
male   completed                 72.339080      70.212644      69.793103
       none                      66.688312      62.795455      59.649351

                                average_score
gender test_preparation_course
female completed                    74.454710
       none                         66.878244
male   completed                    70.781609
       none                         63.044372

In [40]:
# (b) Average scores grouped by parental level of education
avg_by_parent_edu = df.groupby('parental_level_of_education', observed = True)[['math_score', 'reading_score', 'writing_score', 'average_score']].mean()
print("Average scores by Parental Level of Education:")
display(avg_by_parent_edu)

Average scores by Parental Level of Education:

,math_score,reading_score,writing_score,average_score
parental_level_of_education,,,,
associate's degree,67.882883,70.927928,69.896396,69.569069
bachelor's degree,69.389831,73.000000,73.381356,71.923729
high school,62.137755,64.704082,62.448980,63.096939
master's degree,69.745763,75.372881,75.677966,73.598870
some college,67.128319,69.460177,68.840708,68.476401
some high school,63.497207,66.938547,64.888268,65.108007

11. Identify which test preparation group performed best on average (based on
average_score).

In [49]:
# Step 11
best_test_prep = df.groupby('test_preparation_course', observed=True)['average_score'].mean().sort_values(ascending=False)
print("Average performance by Test Preparation Course:")
display(best_test_prep)

best_group = best_test_prep.idxmax()
print(f"The best performing group is: {best_group}")

Average performance by Test Preparation Course:

test_preparation_course
completed    72.669460
none         65.038941
Name: average_score, dtype: float64

The best performing group is: completed

12. Sort the dataset by average_score in descending order and display the top 10
performers.

In [51]:
# Step 12
top_10 = df.sort_values(by='average_score', ascending=False).head(10)
print("Top 10 performers based on Average Score:")
display(top_10)

Top 10 performers based on Average Score:

,gender,race/ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,average_score,performance_category
916,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000,Distinction
962,female,group E,associate's degree,standard,none,100,100,100,100.000000,Distinction
458,female,group E,bachelor's degree,standard,none,100,100,100,100.000000,Distinction
114,female,group E,bachelor's degree,standard,completed,99,100,100,99.666667,Distinction
712,female,group D,some college,standard,none,98,100,99,99.000000,Distinction
179,female,group D,some high school,standard,completed,97,100,100,99.000000,Distinction
165,female,group C,bachelor's degree,standard,completed,96,100,100,98.666667,Distinction
625,male,group D,some college,standard,completed,100,97,99,98.666667,Distinction
685,female,group E,master's degree,standard,completed,94,99,100,97.666667,Distinction
903,female,group D,bachelor's degree,free/reduced,completed,93,100,100,97.666667,Distinction

13. Calculate and print: (a) Number of students in each performance_category, (b)
Percentage of students who completed the test preparation course.

In [52]:
# (a) Number of students in each performance category
performance_counts = df['performance_category'].value_counts()
print("🔹 Number of students in each performance category:")
display(performance_counts)

🔹 Number of students in each performance category:

performance_category
Fail           285
Merit          261
Pass           256
Distinction    198
Name: count, dtype: int64

In [60]:
# (b) Percentage of students who completed the test preparation course
completed_percentage = (df['test_preparation_course'].value_counts(normalize=True) * 100).get('completed', 0)
print(f"Percentage of students who completed the test preparation course: {completed_percentage:.2f}%")

Percentage of students who completed the test preparation course: 35.80%

# **Part 4 — Reflection Questions (10–15 minutes)**

• What insights can you derive about the effect of test preparation on performance?

• Does gender appear to influence performance based on your grouped results?

• How does parental education level relate to student performance?

• What are the limitations of this dataset or your analysis approach?

**Effect of Test Preparation on Performance**

From the results, students who completed the test preparation course got higher marks in almost all subjects as compared to those who didn't complete the test preparation course. So, I think doing the test preperation really helped them to perform better.


**Influence of Gender on Performance**

It looks like males did better in math, but females scored higher in reading and writing. So gender does make some difference in how students perform in different subjects. Maybe it’s because of interest or how they study, not because one is smarter than the other.

**Parental Education Level and Performance**

Students whose parents had more education mostly got better scores. When parents are more educated, they might help their kids more in studies or give them better guidance and support. So I think parental education plays an important role too.

**Limitations of the Dataset or Analysis**

The data sample is small and maybe not from all types of schools or families, so it can’t show everything. Also, just because test preparation students scored higher doesn’t mean test preparation caused it, maybe they were already good students and are motivated. Some other things like school quality, home environment, or interest are not included, so that also affects results.